Feature: Accessibility

  Scenario Outline: Axe tool automation for <site>

    Given I navigate to "<site>"
    When I run axe tool
      | tag      |
      | wcag2a   |
      | wcag2aa  |
      | wcag111  |
      | wcag121  |
      | wcag122  |
      | wcag123  |
      | wcag131  |
      | wcag132  |
      | wcag133  |
      | wcag141  |
      | wcag142  |
      | wcag211  |
      | wcag212  |
      | wcag221  |
      | wcag222  |
      | wcag231  |
      | wcag241  |
      | wcag242  |
      | wcag243  |
      | wcag244  |
      | wcag311  |
      | wcag321  |
      | wcag322  |
      | wcag331  |
      | wcag332  |
      | wcag411  |
      | wcag412  |
      | wcag214  |
      | wcag251  |
      | wcag252  |
      | wcag253  |
      | wcag254  |
      | wcag124  |
      | wcag125  |
      | wcag143  |
      | wcag144  |
      | wcag145  |
      | wcag245  |
      | wcag246  |
      | wcag247  |
      | wcag312  |
      | wcag323  |
      | wcag324  |
      | wcag333  |
      | wcag334  |
      | wcag134  |
      | wcag135  |
      | wcag1410 |
      | wcag1411 |
      | wcag1412 |
      | wcag1413 |
      | wcag413  |
    Then I should get report

    Examples:
      | site                                                           |
#      | main           |
#      | en             |
#      | corporate      |
#      | community      |
#      | readytravel    |
#      | departure      |
#      | arrival        |
#      | accessibility  |
#      | whileyou       |
#      | transportation |
#      | whoweare       |
#      | google   |
#      | tdBank   |
#      | cricbuzz |
      | Purchase_a_Flight_Pass                                         |
      | Car                                                            |
      | Group_Travel                                                   |
      | Where_We_Fly                                                   |
      | Flight_Schedules                                               |
      | Star_Alliance_and_other_Airline_Partners                       |
      | Air_Canada_Rouge                                               |
      | Toronto_Montreal_Ottawa_Service                                |
      | New_Destinations                                               |
      | Featured_Destinations                                          |
      | Express_Service                                                |
      | Celebrate_the_WALT_DISNEY_WORLD_Resort_50th_Anniversary        |
      | Air_Canada_to_The_Magic_Contest                                |
      | Travel_News_and_Updates                                        |
      | Electronic_Travel_Authorization_for_Flights_to_Canada          |
      | News_Archive                                                   |
      | 2018                                                           |
      | 2019                                                           |
      | Goodwill_Policies                                              |
      | 2020                                                           |
      | 2021                                                           |
      | 2022                                                           |
      | Business_Travel                                                |
      | Corporate_Rewards                                              |
      | Join_ACGlobePlus_for_a_chance_to_win_an_Amazon_Echo            |
      | ACGlobe                                                        |
      | ACGlobe_Offer                                                  |
      | Flight_Passes_for_Business                                     |
      | AC_Globe_Card                                                  |
      | Air_Canada_for_Business                                        |
      | Air_Canada_for_Corporate                                       |
      | Air_Canada_Jetz_(Charter_Services)                             |
      | Fare_Options_and_Fees                                          |
      | To_the_US                                                      |
      | To_International_Destinations                                  |
      | To_Sun_Destinations                                            |
      | Within_Canada_with_Rouge                                       |
      | To_the_US_with_Rouge                                           |
      | Within_Canada                                                  |
      | To_international_destinations_with_Rouge                       |
      | To_sun_destinations_with_Rouge                                 |
      | Economy_Flex                                                   |
      | Economy_Basic                                                  |
      | Economy_Fares                                                  |
      | economy_flex                                                   |
      | Gift_Cards                                                     |
      | Manage_Bookings                                                |
      | Flight                                                         |
      | Manage_your_Air_Canada_Flight_Passes                           |
      | Hotel                                                          |
      | Car                                                            |
      | Vacation                                                       |
      | View_Your_Air_Canada_Flight_Pass_Bookings                      |
      | FAQ_manage_my_booking_online                                   |
      | Making_connections_easy                                        |
      | Make_Your_Mark                                                 |
      | Premium_Economy_Class                                          |
      | Premium_Economy_Class                                          |
      | Air_Canada_Flight_Passes                                       |
      | Air_Canada_Upgrades                                            |
      | AC_Bid_Upgrade_FAQs                                            |
      | Last_Minute_Upgrade_Purchase                                   |
      | Payment_Methods                                                |
      | Give_the_Gift_of_Travel                                        |
      | Pay_over_time_with_Uplift                                      |
      | Air_Canada_Loyalty                                             |
      | What_you_need_to_know                                          |
      | Your_Questions                                                 |
      | Thank_you_Air_Canada_Loyalty                                   |
      | Your_Ideas                                                     |
      | Program_Updates                                                |
      | Plan                                                           |
      | Baggage                                                        |
      | Carry_On_Baggage                                               |
      | Checked_Baggage                                                |
      | Special_Items                                                  |
      | Restricted_Prohibited_Items                                    |
      | Delayed_Damaged                                                |
      | Limits_of_Liability                                            |
      | Travel_Requirements                                            |
      | Travel_Documents                                               |
      | Customs_and_Immigration                                        |
      | Advance_Passenger_Information                                  |
      | US_Secure_Flight_Program                                       |
      | TSA Pre                                                        |
      | Special_Assistance                                             |
      | Travelling_with_Children                                       |
      | Travelling_with_your_Pet                                       |
      | Special_Meals                                                  |
      | Meetings_and_Events                                            |
      | Bereavement_Fares                                              |
      | Unaccompanied_Minors                                           |
      | CheckIn_Information                                            |
      | How_to_Check_In                                                |
      | Checkin_Boarding_Times                                         |
      | Minimum_Connection_Times                                       |
      | Check_In_Now                                                   |
      | Medical_Mobility                                               |
      | Advance_Notice_and_Medical_Approval                            |
      | Travelling_with_an_Attendant                                   |
      | Customers_with_Allergies                                       |
      | Visually_or_Hearing_Impaired_Customers                         |
      | Wheelchairs_and_Mobility_Aids                                  |
      | Special_Seating_Needs                                          |
      | Service_Animals                                                |
      | Travelling_with_Oxygen                                         |
      | Washroom_Accessibility                                         |
      | Personal_Oxygen_Concentrators                                  |
      | Portable_Battery_Powered_Medical_Devices                       |
      | Battery_Powered_Mobility_Aids                                  |
      | Complaints_or_Concerns                                         |
      | Peace_of_Mind                                                  |
      | Before_You_Go_Checklist                                        |
      | Health_and_Travel_Tips                                         |
      | Advance_Seat_Selection                                         |
      | Travel_Insurance                                               |
      | On_My_Way_Service                                              |
      | Frequently_Asked_Questions                                     |
      | Family_Travel                                                  |
      | Making_family_travel_more_fun1                                 |
      | Making_family_travel_more_fun2                                 |
      | Travel_options                                                 |
      | Our_accessibility_services                                     |
      | Fly                                                            |
      | Check_In_Now                                                   |
      | At_the_Airport                                                 |
      | Airport_Information                                            |
      | Self_Service_Kiosks                                            |
      | Boarding_by_Zone                                               |
      | Premium_Services                                               |
      | Maple_Leaf_Lounges                                             |
      | Priority_Services                                              |
      | Concierge_Services                                             |
      | Air_Canada_Signature_Suite                                     |
      | Air_Canada_Cafe                                                |
      | Flight_Information                                             |
      | Flight_Status                                                  |
      | Flight_Notification_Service                                    |
      | Delayed_Flight_Cancellations                                   |
      | Pact                                                           |
      | Flight_Status_Results                                          |
      | Flight_Disruptions                                             |
      | Air_Canada_on_your_Mobile                                      |
      | Air_Canada_App                                                 |
      | Mobile_Checkin                                                 |
      | Electronic_Boarding_Passes                                     |
      | Passbook                                                       |
      | Air_Canada_mobile                                              |
      | Air_Canada_Mobile_App                                          |
      | Flight_Pass_App                                                |
      | Wallet                                                         |
      | On_Board                                                       |
      | Air_Canada_Bistro                                              |
      | Our_Fleet                                                      |
      | Cabins_and_Onboard_Meals                                       |
      | Inflight_Entertainment                                         |
      | Preferred_Seats                                                |
      | Wi_Fi                                                          |
      | Duty_Free                                                      |
      | Credit_Card_Only_Cabins                                        |
      | Culinary_Program                                               |
      | Air_Canada_Customer_Support                                    |
      | Frequently_Asked_Questions                                     |
      | Customer_Relations                                             |
      | Receipt_Requests                                               |
      | Contact_Us                                                     |
      | test_ticket                                                    |
      | Contact_Us_Customer_Support                                    |
      | Refund_Services                                                |
      | Air_Canada_Travel_Voucher                                      |
      | Vouchers_ACCredit_and_eCoupons                                 |
      | Air_Canada_Self_serve_support                                  |
      | Debit_memo_policy                                              |
      | Refundable_tax_guide                                           |
      | Help_with_rebooking                                            |
      | Booking_increased_connection                                   |
      | Air_Canada_CRS                                                 |
      | Refund_services_references_guide                               |
      | Achieving_New_Heights                                          |
      | New_Air_Canada                                                 |
      | Fly_the_flag                                                   |
      | Stay_Safe                                                      |
      | Our_Climate_Action_Plan                                        |
      | Legal                                                          |
      | Air_Canada_Customer_Service_Plan                               |
      | General_Condition_of_Carriage                                  |
      | Air_Canada_Privacy_Policy                                      |
      | Terms_of_Use                                                   |
      | Baggage_Fees_and_Optional_Services                             |
      | Air_Canada_Customer_Service_Plan1                              |
      | Air_Canada_Customer_Service_Plan2                              |
      | Contingency_plan_for_lengthy_tarmac_delays_at_Chinese_airports |
      | Cargo_e_AWB                                                    |
      | Thank_you                                                      |
      | Trademarks                                                     |
      | Unsubscribe_Cargo                                              |
      | Home                                                           |